export enum UserStatus {
  WAITING_TEMPLATE = 'WAITING_TEMPLATE',
  WAITING_DATA = 'WAITING_DATA',
  WAITING_FILE = 'WAITING_FILE',
  WAITING_FILE_FOR_SAVE = 'WAITING_FILE_FOR_SAVE',
  WAITING_FILE_FOR_DELETE = 'WAITING_FILE_FOR_DELETE',
}
